### ISSUE TITLE
missing icons and styling on the landingpage

### ISSUE THREAD

**Issue by lucasBRYG** [nickgdam/NutriVice#28]
add fa cdn to main branch, fix styling

**Comment by nickgdam** [comment]
The bug seems to be coming from index.js inside the src folder.  When I remove the bootstrap import, the css is fixed.  The issue with this is our sign in and sign up pages use bootstrap.  Wondering if there is a work around for this, or if we will have to restyle the sign in and sign up pages?

**Comment by nickgdam** [comment]
Solved the issue by moving the bootstrap import to the sign in and sign up pages.
